import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_title': 'Speed Call',
      'keypad': 'Keypad',
      'home_widgets': 'Home Widgets',
      'create_widget': 'Create Widget',
      'select_contact': 'Select Contact',
      'search_contacts': 'Search contacts...',
      'contacts': 'Contacts',
      'favorites': 'Favorites',
      'pinned': 'Pinned',
      'sim_selection': 'SIM Selection',
      'sim_default': 'Android Default SIM',
      'sim_1': 'SIM 1',
      'sim_2': 'SIM 2',
      'sim_ask': 'Ask Every Time',
      'appearance': 'Widget Appearance',
      'background_color': 'Background Color',
      'text_color': 'Text Color',
      'image_shape': 'Image Shape',
      'circular': 'Circular',
      'rounded': 'Rounded',
      'square': 'Square',
      'border_radius': 'Corner Radius',
      'show_name': 'Show Contact Name',
      'show_phone': 'Show Phone Number',
      'widget_size': 'Widget Size',
      'size_small': 'Small (1x1)',
      'size_medium': 'Medium (2x1)',
      'size_large': 'Large (2x2)',
      'pin_to_home': 'Pin to Home Screen',
      'edit_widget': 'Edit Widget',
      'delete_widget': 'Delete Widget',
      'duplicate_widget': 'Duplicate Widget',
      'call_history': 'Call History',
      'filter_all': 'All',
      'filter_missed': 'Missed',
      'filter_outgoing': 'Outgoing',
      'filter_incoming': 'Incoming',
      'call_type_outgoing': 'Outgoing',
      'call_type_incoming': 'Incoming',
      'call_type_missed': 'Missed Call',
      'call_type_rejected': 'Rejected',
      'no_call_history': 'No call history yet',
      'call_history_empty_msg': 'Calls made using Speed Call will appear here automatically.',
      'settings': 'Settings',
      'vibration': 'Vibration Before Call',
      'vibration_desc': 'Provide haptic feedback right before placing direct call',
      'confirmation_dialog': 'Confirm Before Calling',
      'confirmation_desc': 'Show quick confirmation dialog before direct calling',
      'theme': 'App Theme',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_amoled': 'AMOLED',
      'theme_system': 'System Default',
      'dynamic_colors': 'Material You Dynamic Colors',
      'language': 'Language',
      'arabic': 'العربية (Arabic)',
      'english': 'English',
      'permissions': 'Permissions',
      'permission_contacts_desc': 'Required to pick contacts and photos for widgets.',
      'permission_call_desc': 'Required to place direct one-tap phone calls without opening dialer.',
      'grant_permission': 'Grant Permission',
      'no_widgets_yet': 'No direct dial widgets created yet.',
      'tap_plus_to_create': 'Tap + below to create your first home screen widget!',
      'direct_call_now': 'Call Now',
      'cat_speed_dial': 'Speed Dial & Shortcuts',
      'manage_speed_dial_keys': 'Manage 1-9 Speed Dial Keys',
      'manage_speed_dial_sub': 'Assign contacts & SIM preferences to keypad keys 1-9',
      'cat_safety': 'Safety & Protection',
      'family_sos': 'Family Emergency SOS',
      'family_sos_sub': 'Configure Family SOS Widget, Calls & Alerts',
      'blocked_contacts': 'Blocked Contacts & Spam',
      'blocked_contacts_sub': 'Manage blacklisted phone numbers',
      'analytics': 'Call Statistics & Analytics',
      'analytics_sub': 'View call frequency and top contacts',
      'cat_appearance': 'Appearance & Language',
      'cat_calling_prefs': 'Calling Preferences',
      'cat_developer': 'Developer & App Info',
      'about_developer': 'About Developer',
      'about_developer_sub': 'Mohamed Sabry • Connect & Contact Info',
    },
    'ar': {
      'app_title': 'الاتصال السريع',
      'keypad': 'الكيبورد',
      'home_widgets': 'عناصر الشاشة الرئيسية (الودجتس)',
      'create_widget': 'إنشاء ودجت جديد',
      'select_contact': 'اختر جهة الاتصال',
      'search_contacts': 'البحث في الأسماء والأرقام...',
      'contacts': 'جهات الاتصال',
      'favorites': 'المفضلة',
      'pinned': 'المعلّقة والمثبتة',
      'sim_selection': 'تحديد شريحة الاتصال (SIM)',
      'sim_default': 'الشريحة الافتراضية للنظام',
      'sim_1': 'شريحة 1',
      'sim_2': 'شريحة 2',
      'sim_ask': 'السؤال واختيار الشريحة في كل مرة',
      'appearance': 'مظهر وتنسيق الودجت',
      'background_color': 'لون الخلفية',
      'text_color': 'لون النص والخط',
      'image_shape': 'شكل صورة الشخص',
      'circular': 'دائري كامل',
      'rounded': 'زوايا دائرية مرنة',
      'square': 'مربع كلاسيكي',
      'border_radius': 'درجة انحناء الزوايا',
      'show_name': 'إظهار اسم الشخص',
      'show_phone': 'إظهار رقم الهاتف',
      'widget_size': 'حجم الودجت على الشاشة',
      'size_small': 'صغير (1x1)',
      'size_medium': 'متوسط (2x1)',
      'size_large': 'كبير (2x2)',
      'pin_to_home': 'تثبيت في الشاشة الرئيسية للهاتف',
      'edit_widget': 'تعديل الودجت',
      'delete_widget': 'حذف الودجت',
      'duplicate_widget': 'تكرار الودجت',
      'call_history': 'سجل المكالمات',
      'filter_all': 'الكل',
      'filter_missed': 'مفقودة',
      'filter_outgoing': 'صادرة',
      'filter_incoming': 'واردة',
      'call_type_outgoing': 'مكالمة صادرة',
      'call_type_incoming': 'مكالمة واردة',
      'call_type_missed': 'مكالمة مفقودة',
      'call_type_rejected': 'مكالمة مرفوضة',
      'no_call_history': 'لا يوجد سجل مكالمات بعد',
      'call_history_empty_msg': 'المكالمات التي تجريها عبر التطبيق ستظهر هنا تلقائياً.',
      'settings': 'الإعدادات',
      'vibration': 'الاهتزاز التنبيهي قبل الاتصال',
      'vibration_desc': 'تشغيل اهتزاز تفاعلي خفيف قبل الاتصال المباشر',
      'confirmation_dialog': 'التأكيد التفاعلي قبل المكالمة',
      'confirmation_desc': 'إظهار نافذة تأكيد سريعة قبل الاتصال المباشر',
      'theme': 'مظهر وألوان التطبيق',
      'theme_light': 'فاتح (نهارى)',
      'theme_dark': 'داكن (ليلي)',
      'theme_amoled': 'شاشة سواد تام (AMOLED)',
      'theme_system': 'حسب إعدادات النظام',
      'dynamic_colors': 'ألوان Material You الديناميكية',
      'language': 'لغة التطبيق',
      'arabic': 'العربية (Arabic)',
      'english': 'English',
      'permissions': 'صلاحيات التشغيل',
      'permission_contacts_desc': 'مطلوبة للوصول إلى أسماء وصور ورقم الأشخاص لإنشاء الودجتس.',
      'permission_call_desc': 'مطلوبة لإجراء المكالمة التلفونية المباشرة بنقرة واحدة بدون فتح لوحة الاتصال.',
      'grant_permission': 'الموافقة ومنح الصلاحية',
      'no_widgets_yet': 'لم يتم إنشاء أي ودجت اتصال بعد.',
      'tap_plus_to_create': 'اضغط على زر + أدناه لإنشاء أول ودجت لشاشتك الرئيسية!',
      'direct_call_now': 'اتصل الآن',
      'cat_speed_dial': 'الاتصال السريع والاختصارات',
      'manage_speed_dial_keys': 'إدارة أزرار الاتصال السريع (1-9)',
      'manage_speed_dial_sub': 'تعيين جهات الاتصال والشريحة المفضلة لأزرار الكيبورد 1-9',
      'cat_safety': 'الأمان وطوارئ العائلة',
      'family_sos': 'طوارئ العائلة (Family SOS)',
      'family_sos_sub': 'ضبط إعدادات ودجت ومكالمات ورسائل الاستغاثة',
      'blocked_contacts': 'جهات الاتصال المحظورة والسبام',
      'blocked_contacts_sub': 'إدارة الأرقام والقائمة السوداء',
      'analytics': 'إحصائيات وتحليلات المكالمات',
      'analytics_sub': 'عرض تكرار المكالمات وأكثر الأسماء اتصالاتً',
      'cat_appearance': 'المظهر ولغة التطبيق',
      'cat_calling_prefs': 'تفضيلات الاتصال والاهتزاز',
      'cat_developer': 'عن المطور والتطبيق',
      'about_developer': 'معلومات المطور',
      'about_developer_sub': 'محمد صبري • معلومات التواصل والبرمجة',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
